project_id = "nxtnonfxxophicxewkmw"

[functions.proxy-image]
verify_jwt = false

[functions.storage-cleanup]
verify_jwt = true

[functions.check-spam]
verify_jwt = true

[functions.delete-all-posts]
verify_jwt = true
